import { Mail, ShieldCheck, UserRound, Save } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import { useState } from 'react'
import { usersApi } from '../api/endpoints/users.api'
import toast from 'react-hot-toast'
import axios from 'axios'

export const ProfilePage = () => {
  const { user, setUser } = useAuth()
  const [fullName, setFullName] = useState(user?.fullName || '')
  const [email, setEmail] = useState(user?.email || '')
  const [password, setPassword] = useState('')
  const [isSaving, setIsSaving] = useState(false)
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!user) return; if (password && password.length < 8) { toast.error('Password must be at least 8 characters'); return }; setIsSaving(true); try { const updated = await usersApi.update(user.id, { fullName, email, ...(password ? { password } : {}) }); setUser(updated); setPassword(''); toast.success('Account updated successfully') } catch (error: unknown) { toast.error(axios.isAxiosError(error) ? error.response?.data?.message || 'Unable to update account' : 'Unable to update account') } finally { setIsSaving(false) } }
  return <div className="mx-auto max-w-3xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-widest text-cyan-700">Account</p><h1 className="mt-1 text-3xl font-semibold text-slate-950">Your profile</h1><p className="mt-2 text-sm text-slate-500">Update your identity and password for the current PlayHouse account.</p></div><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-4 border-b border-slate-100 pb-6"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-cyan-100 text-xl font-bold text-cyan-800">{user?.fullName?.charAt(0) || 'U'}</div><div><h2 className="text-xl font-semibold text-slate-950">{user?.fullName || 'User'}</h2><p className="text-sm text-slate-500">{user?.role || 'Account'}</p></div></div><form className="grid gap-4 pt-6" onSubmit={save}><label className="text-sm font-medium text-slate-700">Full name<input className="input-field mt-1" value={fullName} onChange={(event) => setFullName(event.target.value)} required /></label><label className="text-sm font-medium text-slate-700">Email address<input className="input-field mt-1" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label className="text-sm font-medium text-slate-700">New password<input className="input-field mt-1" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Leave blank to keep current password" /></label><div className="flex justify-end"><button className="btn-primary inline-flex items-center gap-2" disabled={isSaving}><Save className="h-4 w-4" />{isSaving ? 'Saving...' : 'Save changes'}</button></div></form><dl className="mt-6 grid gap-5 border-t border-slate-100 pt-6 sm:grid-cols-2"><Detail icon={<Mail className="h-4 w-4" />} label="Email address" value={user?.email || '-'} /><Detail icon={<ShieldCheck className="h-4 w-4" />} label="Access role" value={user?.role || '-'} /><Detail icon={<UserRound className="h-4 w-4" />} label="Account status" value={user?.status || '-'} /><Detail icon={<UserRound className="h-4 w-4" />} label="Member since" value={user?.createdAt ? new Date(user.createdAt).toLocaleDateString() : '-'} /></dl></section></div>
}

function Detail({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div><dt className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500">{icon}{label}</dt><dd className="mt-1 text-sm font-medium text-slate-900">{value}</dd></div> }
